### ISSUE TITLE
Mouse settings not applied after disconnect/reconnect (3.38)

### ISSUE THREAD

**Issue by pkactual** [pop-os/gnome-control-center#120]
After the latest POP 20.04 updates on a DARP6, gnome-control-center 3.38.0 shows the _right_ mouse settings but it's always using the faster speed, 'wrong' scroll, and acceleration profile. It shows whatever you've set but you have to toggle them and move the slider each boot or coming out of suspend to get it back to where you want it. This seems to affect both an external mouse and touchpad.

**Comment by jacobgkau** [comment]
I've replicated this with a Bluetooth mouse on both the galp4 and the addw2. On galp4, the "Mouse" section of the Mouse & Touchpad page goes away when the mouse is disconnected; on the addw2, the "Mouse" section stays there whether it's connected or not (I'm assuming that's an NVIDIA thing, this testing was in Hybrid mode.) On both devices, if I change some settings, power off the mouse long enough for the Bluetooth connection to disconnect, then power it back on, the settings _appear_ to load back to their proper values on the galp4 (and do not change on the addw2), but those values don't actually take effect until each one's changed again. (gsettings shows the values are being stored properly; for example, after disconnecting/reconnecting the mouse, Natural Scrolling still shows as `true` even though it's not taking effect.)

This doesn't happen on `1:3.36.4-0ubuntu1pop1~1596049125~20.04~426adb3`, but it does happen on `1:3.38.0-1ubuntu1pop1~1601923341~20.04~97db3d4`. (On 3.36, there is a very brief delay after connecting the mouse before the settings are loaded/applied.) This is also happening on pre-release Pop!_OS 20.10 with `1:3.38.0~1ubuntu1pop1~1600878607~20.10~d3d56ba`.

We've got a customer report that their Logitech mouse has this issue when connecting via Bluetooth, but does not have the issue when connecting via the USB wireless adapter; contrary to that report, I'm seeing it happen when I unplug/re-plug a USB mouse as well. I am seeing the issue occur on the galp4 touchpad after suspending/resuming (20.04), but not the addw2 touchpad after suspending/resuming (20.10).

**Comment by pkactual** [comment]
Customer with the report here - I've tried to replicate it with my Pebble and the USB and can't. Turn it off/on during use, suspend, boot, etc. and it doesn't happen. BT happens every time now after that recent update. Unfortunately I have two of the same Pebble and no other mouse to try it with.

I'm *confident* it happened with the integrated touchpad the first few days but hasn't happened since another update. It _does_ happen if it's also happening to the BT mouse but when I turn BT off and just use the touchpad, it doesn't happen. DARP6, POP 20.04 w/ latest patches (as of today, tried numerous iterations before posting this update).

**Comment by evilthreads669966** [comment]
- I purchased a gazelle system76 laptop with POP OS 20.04. The webcam disappeared and no longer showed up in my browsers. I then checked the Cheese app off the POP shop as I had been using it frequently for making videos back in September. I don't know how to fix it.
- I just had an issue with my wifi card after installing system updates from the POP SHOP UI. I turned off my laptop and came back in and my mouse sensitivty setting was at 100% and it still doesn't feel right. I was trying to see if there was a way to revert back to the default settings. I even disabled my touchpad in the settings and it still works and for some reason the mouse sensitivity is the one dictating which is controlling the driver. Then I discovered they each play a part in the sensitity. 
- Thanks guys I love the laptop for Android though although I wish to go back to Ubuntu because I don't know any of the desktop shortcuts.

**Comment by evilthreads669966** [comment]
I purchased a gazelle system76 laptop with POP OS 20.04. The webcam disappeared and no longer showed up in my brow

**Comment by evilthreads669966** [comment]
now your pop shop is telling me to instal 
• org.freedesktop.Platform Flatpak runtime
 • org.freedesktop.Platform Flatpak runtime
 • org.freedesktop.Sdk Flatpak runtime
 • org.freedesktop.Sdk Flatpak runtime
 • org.gnome.Platform Flatpak runtime
 • org.gnome.Platform Flatpak runtime
 • org.gnome.Platform Flatpak runtime
 • org.kde.Platform Flatpak runtime
 • org.kde.Platform Flatpak runtime

**Comment by jacobgkau** [comment]
The issue is present in Ubuntu 20.10 beta (with gnome-control-center `1:3.38.1-1ubuntu1` and gnome-settings-daemon `3.38.0-1ubuntu1pop0~1600884218~20.10~971327c~dev` or `3.38.0-1ubuntu1`), but not Fedora 33 beta (with gnome-control-center `3.38.1` and gnome-settings-daemon `3.38.1`.)

The issue also does not occur on Debian Testing (bullseye) with gnome-control-center `1:3.38.1-1` and gnome-settings-daemon `3.38.0-2`, so this may be introduced by an Ubuntu patch.

**Comment by jacobgkau** [comment]
I built gnome-settings-daemon without any patches applied except for `meson.build-Lower-polkit-requirement.patch` (which is required for building), and the issue still occurs. Also tried disabling all Ubuntu patches in gnome-control-center except for `0021-Revert-build-Bump-build-dependency-on-polkit.patch`, still seeing the issue. Could be something in mutter or gnome-shell? (Or a difference in one of the settings packages I'm overlooking.)

**Comment by ids1024** [comment]
Mutter perhaps. I doubt it would be Gnome Shell.

Fedora defaults to Wayland, and Ubuntu still defaults to Xorg, right? Don't know about Debian. Input device handling is potentially different between the two.

**Comment by jacobgkau** [comment]
> Fedora defaults to Wayland, and Ubuntu still defaults to Xorg, right? Don't know about Debian. Input device handling is potentially different between the two.

Of course, that was it. Fedora was defaulting to Wayland, after switching to Xorg I see the issue there too. Same on Debian.

I've located upstream issues in both the GCC and GSD repos and added the detail we have. GCC: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1145 

GSD: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/559

**Comment by ids1024** [comment]
It looks like there was only one trivial change to the Gnome Control Center mouse panel between 3.36 and 3.38, so I don't think the issue is in Gnome Control Center. Probably not Gnome Settings Daemon either.

It seems the mouse panel sets values in the `org.gnome.desktop.peripherals.mouse` gsettings schema, which is handled [by mutter](https://gitlab.gnome.org/GNOME/mutter/-/blob/master/src/backends/meta-input-settings.c). So the issue is probably in Mutter (which is also suggested by differing behavior on Xorg and Wayland).

Debugging issues with Mutter is a pain... Is there any version we know to be working? If it was working until a recent update, I guess that would be the last updated to the Pop!_OS `mutter` package, which appears to have been September 29 (from `/usr/share/doc/mutter/changelog.Debian.gz`).

**Comment by mmstick** [comment]
My first guess would be a debian patch

**Comment by mcajina74** [comment]
I'm seeing this issue in both Pop!_OS 20.04 (Gnome 3.36.3) and 20.10 (3.38). I've only experienced it with my Bluetooth Logitech mouse (MX Ergo).

I think it started after a recent update to 20.04, but now I don't remember which one. I'm inclined to say that it was OK on 20.04 at first. I did not have this issue with Pop!_OS 19.10. I'm sorry I can't be more specific. I no longer have the ISOs to try a fresh install of Pop!_OS 20.04 from before the latest updates.

**Comment by waltyl14** [comment]
Like mcajina74 I have experienced this issue on both Pop!_OS 20.04 (Gnome 3.36.3) and 20.10 (3.38). My wireless USB mouse, connected by way of a USB-C dock is affected and every time I wake from a suspend I have to toggle acceleration and natural scrolling settings one full cycle in order to have the settings match the experience. When still running 20.04 I time shifted back to Oct 4th and still experienced the issue. So, I believe this problem originates from before that date...

**Comment by cpswaim** [comment]
I came across this issue by googling "natural scrolling ubuntu" with a time constraint of 9/1+, as I recently started seeing this issue. I have noticed my mouse speed and natural scrolling settings need to be toggled / touched every time I dock even though they display the correct settings. Easily able to replicate by plugging mouse USB dongle into my laptop, correcting settings, unplugging and replugging USB - settings are now displaying the previously set values but with scrolling & mouse speed incorrect.

Kernel 5.4.0-52-generic
Ubuntu 20.04
gnome-control-center 3.36.4
Dell Latitude 7300 & 7400

This makes me think it's not specific to Pop!_OS.

**Comment by ids1024** [comment]
Yep, it doesn't seem to be Pop!_OS specific. Perhaps you could submit that report on the upstream issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/1505

It would be good to narrow down what updated caused this issue. Mutter seems likely, but looking at it I didn't see any recent changes that seem related.

**Comment by jacobgkau** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1553 - An upstream merge request has been merged to fix this issue. It [sounds](https://gitlab.gnome.org/GNOME/mutter/-/issues/1505#note_957140) like it will be included in the next stable release of Mutter on November 21st.

**Comment by mcajina74** [comment]
Has this been fixed yet? I've applied every update for Pop!_OS 20.04 LTS (Gnome 3.36.3 X11) since I first posted on Oct 30, and I still have this issue.

**Comment by ids1024** [comment]
I believe Mutter 3.38.2 (on Pop!_OS 20.10) and 3.36.8 (on Pop!_OS 20.04) should have the fix. Which I believe are supposed to be released now, but haven't been tagged yet upstream.

Pop!_OS will update those packages once Gnome releases them.

**Comment by mcajina74** [comment]
@ids1024 , Thank you. I wasn't sure if I missed something. I'll keep looking out for new updates. I really don't want to switch to another DE. Everything in Pop!_OS seems to be optimized for Gnome.

**Comment by waltyl14** [comment]
> @ids1024 , Thank you. I wasn't sure if I missed something. I'll keep looking out for new updates. I really don't want to switch to another DE. Everything in Pop!_OS seems to be optimized for Gnome.

Pretty sure its fixed now. I got a mutter update through PopShop that seemed to take care of the issue (i.e. I have not experienced it with the last dock/undock cycles)!

**Comment by mcajina74** [comment]
It's still not working for me. I just applied some updates, and then rebooted. When I logged back in, both my Bluetooth mouse and keyboard stalled for a couple of seconds and then reconnected. This is the behavior that precedes losing the "natural scrolling" setting.

**Comment by mmstick** [comment]
@mcajina74 The 3.38.2 update hasn't been merged yet

**Comment by mcajina74** [comment]
@mmstick Ah, I see. I was going to add that it looks like the mutter version I have installed is 3.36.6 (Ubuntu/Pop 20.04). I'll just wait for the 3.36.8 update, then.

**Comment by pkactual** [comment]
One of the recent updates on POP_OS 20.04 inherited a new problem along these lines - it keeps turning back on the trackpad even if we've Fn-disabled it. Coming out of suspend, new boot, always re-enabled again. Along with resetting the Bluetooth mouse settings.

**Comment by ids1024** [comment]
Pop!_OS 20.10 now packages Mutter 3.38.2, and we've backported the fix on 20.04 since it's not clear when upstream Mutter will tag a new 3.36.x release. So this should be fixed now.

**Comment by ids1024** [comment]
Closing, since this should be addressed on both 20.04 and 20.10, and hopefully won't be an issue any further.

**Comment by CharlesYinchuDong** [comment]
Hello! I'm still seeing this issue with:
OS: Ubuntu 20.10
GNOME: 3.38.1
I'm curious to know is this expected? If so, where can I keep track of the fix?
Thank you!!

**Comment by ids1024** [comment]
@CharlesYinchuDong That's expected if Ubuntu is still packaging Mutter 3.38.1. It's fixed in Mutter 3.38.2.

**Comment by CharlesYinchuDong** [comment]
@ids1024 Thank you very much!! I have confirmed that I'm using Mutter 3.38.1 by running `apt-cache show mutter | grep Version`.
